# dispatch-queue-mode

* 写这个项目的原因

- 如何学习就是是如何合理分配时间，合理分配资源的策略

    - 背景

      脱离了高中后，我大学的前面 3 年，都处于一种低效的自学模式。

      经常感觉时间不够用，怎么这个还没有学完，另一门科目就要考试了？我把整本 《C++ Primer》都啃完了，但是考 c++ 还是拉垮，这是为啥？

      同时我观察很多同学，包括考第一名的学委，考试很行，但是也就考试还行。而且一旦脱离了考试的范围，或者换个出题老师，基本 gg。

      所以，我思考，造成这些问题的原因是啥？那到底怎么才算是学习？怎么样才算是真的学会？
      
    - 思考的结果 - 学习应该是实践驱动的

      什么是学习，那提高自身的生产力，用于实践。实践可以是考试，为老板创造价值，贡献社会等。

      也就是说，学习是需要结合实际的，为具体实践服务的。你不能假设自己的时间无限，精力无限，像武侠小说一样，闭关钻研个几年成为高手，天下武学尽在掌握，这是不现实的。

      学习是如何合理分配时间，合理分配资源的一种策略。用一个成语形容，那就是 '以战养战‘。
      
      当你接手一个限时 1 个月 C++ 任务时，你不懂 C++ 。那么你该听从知乎大神的建议去读一本 《C++ Primer》？ 还是读一本轻薄的《Essential C++》？ 如果选择的是前者，不妨思考，就算把 《C++ Primer》啃完了，就真的学会 C++ 吗？ 

      知识是永远也学不完的，但是对于这个任务而言，怎么合理安排时间是更加重要的事情，有的任务需要你达到 80% 的水平，而有的任务只需要 60% 的水平，但是有时间限制。

- Org-mode 太过于复杂

  我使用了两个月的 org-agenda 作为 gtd 工具，我感慨他的强大，但是带给我巨大的心智负担。

    1. 过于灵活，我没有找到一种统一的最佳实践，他就像把食材给你，但是怎么炒，没有教你。以至于用法五花八门，你也不知道是不是适合自己，就套着用。

    2. 太多看起来很有用的功能，但是实际没有啥用，反而给我带来很多无用干扰信息

    3. GTD 看起来很美好，实际没有啥用。

- 目标

    - 只有一种，唯一的最佳实践，没有多余用法，增加心智负担

    - 简单，只提供必要的信息

    - 自动任务调度

      
* 需求分析

  - 以建立知识库为核心

    不少使用者，是根据时间线来叙述的
    #+begin_src org
      ,* TODO 2022.11.26
      ,** TODO A 
      ,** TODO B
      ,* TODO 2022.11.27
    #+end_src

    正确的思路是
    #+begin_src org
      ,* TODO Python
      ,** TODO Python 网络编程
      SCHEDULED: <2022.11.26>
       - [ ] aiohttp
         xxoo
       - [ ] async/await
         xxoo
      ,** TODO Python 数据库
      SCHEDULED: <2022.11.27>
    #+end_src

    这样做的好处很多，方便再次规划新任务，方便重新调整，例如你很容易就发现，python 网络编程还有有一个新子任务，Selector 基础，你可以添加上去，即时你现在没空学，但是日后，你很容易发现有个 todo 没有做。
    
  - 使用不同文件划分不同的场景，且有一个核心 base 文件进行同步
    
      - school.org  针对学校任务。例如学校考试，主要是靠看老师的题库，根据学校所用教科书的思路，有种学文科的感觉
      - company.org 针对公司任务
      - base.org 核心知识

        规划时间，把不同任务所学的知识点，整理，同步到这里，作为核心的知识库。

        当遇到一个新任务，先复习 base.org, 从里面的知识点为基础，增加自己下一次的学习速度。或者参考上次任务的学习经验。
        
        不管是学校考试，还是公司任务，还是平时看书，总是有核心的共通点，例如计算机网络，只是需要理解范围不同，例如学校考试主要是背诵概念，公司后端主要理解 tcp ，平时看书也陆陆续续学到了不少新东西，那就把他们总结下吧。
        
  - 分配任务，而不是记录日志。
    
    打几个时间戳，记录今天多少点做了什么，在我看来，除了让自己感动，没有啥意义

  - 记录每件事完成时间，用于分析时间，重新调整任务优先级
        
  - 多线程：同时做多件事情
    研究证明，单线程模式的学习效率比多线程差的远了。

    而且不仅是学习效率的角度，从长远的角度，多线程非常重要。当你很忙的时候，能够把零碎时间挤出来，去做其余任务，并且能够 tag 进度，花时间总结，别小看每天那么丁点时间，坚持下来会产生质变

* 对 org-mode 的简化
  - 只做超长时间的学习任务
    
    不要什么鸡毛蒜皮小事，例如多少点开会，多少点交表都打个 TODO 标签，这叫什么，脱下裤子放屁，还污染了知识库。

  - 只有三种状态，WAIT, ACTIVITY, DONE

    我看博客看到很多使用者设置了各种状态，有那么多状态，肯定势必分了很多短任务吧。我也试过，一超时，全乱了，有 wait 的，有 stop 的，有 todo 的，有 bug 的，我该做那个呢？新进入的任务怎么划分时间呢？
    
    我认为没有必要。前面说过，只做长任务，而每个任务都是需要几天，几个星期去完成的。但是不可能几天都重复只做那么一件事情。

    那么肯定是只有三种状态，

      - WAIT

        因为此时手头的活太多了，或者需要等待别人，所以占个位置，等待你空闲时去开启

      - ACTIVITY

        激活状态，相当于进入队列，允许 3-5 任务进入队列，进入队列后，记录不同任务的使用时间，根据反馈信息，灵活的把时间段划分。

      - DONE
        
        完成状态

  - 起始时间与截止时间 
  
* 调度队列


