# dispatch-queue-mode

* 写这个项目的原因

- 如何学习就是是如何合理分配时间，合理分配资源的策略

    - 背景

      脱离了高中后，我大学的前面 3 年，都处于一种低效的自学模式。

      经常感觉时间不够用，怎么这个还没有学完，另一门科目就要考试了？我把整本 《C++ Primer》都啃完了，但是考 c++ 还是拉垮，这是为啥？

      同时我观察很多同学，包括考第一名的学委，考试很行，但是也就考试还行。而且一旦脱离了考试的范围，或者换个出题老师，基本 gg。

      所以，我思考，造成这些问题的原因是啥？那到底怎么才算是学习？怎么样才算是真的学会？
      
    - 思考的结果 - 学习应该是实践驱动的

      什么是学习，那提高自身的生产力，用于实践。实践可以是考试，为老板创造价值，贡献社会等。

      也就是说，学习是需要结合实际的，为具体实践服务的。你不能假设自己的时间无限，精力无限，像武侠小说一样，闭关钻研个几年成为高手，天下武学尽在掌握，这是不现实的。

      学习是如何合理分配时间，合理分配资源的一种策略。用一个成语形容，那就是 '以战养战‘。
      
      当你接手一个限时 1 个月 C++ 任务时，你不懂 C++ 。那么你该听从知乎大神的建议去读一本 《C++ Primer》？ 还是读一本轻薄的《Essential C++》？ 如果选择的是前者，不妨思考，就算把 《C++ Primer》啃完了，就真的学会 C++ 吗？ 

      知识是永远也学不完的，但是对于这个任务而言，怎么合理安排时间是更加重要的事情，有的任务需要你达到 80% 的水平，而有的任务只需要 60% 的水平，但是有时间限制。

- Org-mode 太过于复杂

  我使用了两个月的 org-agenda 作为 gtd 工具，我感慨他的强大，但是带给我巨大的心智负担。

    1. 过于灵活，我没有找到一种统一的最佳实践，他就像把食材给你，但是怎么炒，没有教你。以至于用法五花八门，你也不知道是不是适合自己，就套着用。

    2. 太多看起来很有用的功能，但是实际没有啥用，反而给我带来很多无用干扰信息

    3. GTD 看起来很美好，实际没有啥用。

- 目标

    - 只有一种，唯一的最佳实践，没有多余用法，增加心智负担

    - 简单，只提供必要的信息

    - 自动任务调度

* 我对 dispatch 的理解
  - 

  - 
      - 一次

        研究证明，单线程模式的学习效率比多线程差的远了。

        而且不仅是学习效率的角度，从长远的角度，多线程非常重要。当你很忙的时候，能够把零碎时间挤出来，去做其余任务，并且能够 tag 进度，花时间总结，别小看每天那么丁点时间，坚持下来会产生质变
  
      - 


